/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scovionatto;

import java.awt.image.ImageObserver;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;
//import  org.apache.poi.hssf.usermodel.HSSFSheet;
//import  org.apache.poi.hssf.usermodel.HSSFWorkbook;
//import  org.apache.poi.hssf.usermodel.HSSFRow;
//import  org.apache.poi.hssf.usermodel.HSSFCell;
//import org.apache.poi.ss.usermodel.Workbook;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author Diogo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scovionatto/hoodball.jpg"))); // NOI18N

        jButton2.setText("Duração do campeonato");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sorteio dos times");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Sorteio da tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("Sorteio da tabela");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String valor1 = JOptionPane.showInputDialog("Número de jogadores do campeonato:");
    int valor1int = Integer.parseInt(valor1);
    
    int total=0;
    int n=0;
    int tempo;
    int tempomin = 0;
    
//    if (valor1int <= 8) {
    
    for (int y = 1; y<valor1int; y++){
            n++;
            total = total + n;
        }
    
    tempo = 10 * total;
    
    String totalS = Integer.toString(total);
    String mTotal = String.format ("Número total de partidas: %s \n", totalS); 
    

    if (tempo > 60) {
            tempomin = tempo%60;
            tempo = tempo/60;
            String tempoS = Integer.toString(tempo);
            String tempominS = Integer.toString(tempomin);
            String mTempo = String.format ("Duração do campeonato é de %s horas e %s minutos\n ",tempoS,tempominS);
            JOptionPane.showMessageDialog(null, mTotal);
            JOptionPane.showMessageDialog(null, mTempo);
        }
        else {
        tempo = tempo;
        String tempoS = Integer.toString(tempo);
        String mTempoP = String.format ("Duração do campeonato é de: %s minutos\n ",tempoS);
        JOptionPane.showMessageDialog(null, mTotal);
        JOptionPane.showMessageDialog(null, mTempoP);
    }
    
//    }
    
//    else {
//            JOptionPane.showMessageDialog(null, "Selecione até 8 jogadores!\n");
//            }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String valor1 = JOptionPane.showInputDialog("Número de jogadores do campeonato:");
        int valor1int = Integer.parseInt(valor1);
        
        if (valor1int <= 9) {
      
        String[] times = new String[valor1int];
        String[] times2 = new String[valor1int];
       
        String mostraParticipante = "";
        
        for (int i = 0; i<valor1int; i++) {
            String valor2 = JOptionPane.showInputDialog("Nome do participante:");
            times [i] = valor2;
            //Trecho para exibir os nomes dos participantes numa tela separada
            String mParticipante = String.format ("Participante: %s\n",times[i]);
            mostraParticipante = mostraParticipante + mParticipante;
            
        }
        
        //Exibe os nomes dos participantes na tela separada
        JOptionPane.showMessageDialog(null, mostraParticipante);
        
        //inicio da construcao com vetor 
        for (int i = 0; i<valor1int; i++) {
            String valor3 = JOptionPane.showInputDialog("Nome do time:");
            times2 [i] = valor3;
            
        }       
        
        List<String> selecoes = new ArrayList<>();
        
        for (int i = 0; i<valor1int; i++) {
        
        selecoes.add(times2[i]);
     
        }
        
        
//Embaralhamos as selecoes:  
Collections.shuffle(selecoes);  

  
for (int i = 0; i < valor1int; i++) {  
     String mParticipante = String.format ("Participante: %s\n",times[i]);
     String mTime = String.format ("Seleção: %s\n",selecoes.get(i));
     String mensagemTotal = String.format("%s \n %s \n", mParticipante, mTime);
    JOptionPane.showMessageDialog(null, mensagemTotal);
  
}  

        }
        
    else {
            JOptionPane.showMessageDialog(null, "Selecione até 9 jogadores!\n");
            }    
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {List<String> clubes = new ArrayList<String>();
    String valor1 = JOptionPane.showInputDialog("Número de jogadores do campeonato:");
    String resultado = "";
    int valor1int = Integer.parseInt(valor1);
    for (int i = 0; i<valor1int; i++) {
        String clube1 = JOptionPane.showInputDialog("Nome do participante:");
        clubes.add(clube1);
    }
    if (clubes.size() % 2 == 1) {
        clubes.add(0, "");
    }
    int t = clubes.size();
    int m = clubes.size() / 2;
    String[] rodada = new String[valor1int];
    for (int i = 0; i < t - 1; i++) {
        
//                HSSFRow row = sheet.createRow((short)i);
//                row.createCell(0).setCellValue((i+1)+"a rodada: ");

String mRodada = String.format("%sa rodada:",(i+1));
rodada [i] = mRodada;
for (int j = 0; j < m; j++) {
    //Clube está de fora nessa rodada?
    if (clubes.get(j).isEmpty())
        continue;
    
    //Teste para ajustar o mando de campo
    if (j % 2 == 1 || i % 2 == 1 && j == 0)  {
//                        row.createCell(j+1).setCellValue(clubes.get(t - j - 1) + " x " + clubes.get(j) + "   ");
String mClube1 = String.format(" %s x %s \n",clubes.get(t - j - 1),clubes.get(j));
String mensagemTotalrodada = String.format ("%s %s",mRodada,mClube1);
resultado = resultado + mensagemTotalrodada + "";
    }
    
    else  {
//                        row.createCell(j+1).setCellValue(clubes.get(j) + " x " + clubes.get(t - j - 1) + "   ");
String mClube1 = String.format(" %s x %s \n",clubes.get(j),clubes.get(t - j - 1));
String mensagemTotalrodada = String.format ("%s %s",mRodada,mClube1);
resultado = resultado + mensagemTotalrodada + "";
    }
}

//Gira os clubes no sentido horário, mantendo o primeiro no lugar
clubes.add(1, clubes.remove(clubes.size()-1));
    }
    JOptionPane.showMessageDialog(null, resultado);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
